# https://github.com/NixOS/nixos-artwork/blob/35ebbbf01c3119005ed180726c388a01d4d1100c/logo/README.md#L5
name: ❄️
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/nix.yml'
      - '**.nix'
      - 'flake.*'
      - 'Taskfile.yml'
  pull_request:
    paths:
      - '.github/workflows/nix.yml'
      - '**.nix'
      - 'flake.*'
      - 'Taskfile.yml'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  tasks:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - run: nix develop --command echo 'This step should be done before any other "nix develop" steps because of measuring Nix build time'
      - run: nix flake check
      - run: nix flake show
      - run: nix develop --command task deps
      - run: nix develop --command task lint
